import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Roboto} from 'next/font/google'
const roboto = Roboto({subsets: ['vietnamese'], weight:['100','200','300', '400','500']})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next New App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${roboto.className} antialiased`}>
              {children}
        </body>
      </html>
  );
}
